In [10]:
#Step 1 import the data
#step 2 clean the data
# step 3 split the data into training/tests sets
# Step 4 create a model
# step 5 make the predictions
# step 6 evaluate and improve

In [26]:
# step 1 import the date
# step 2 is already done
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

music_data = pd.read_csv('music.csv')
music_data

    age  gender      genre
0    20       1     HipHop
1    23       1     HipHop
2    25       1     HipHop
3    26       1       Jazz
4    29       1       Jazz
5    30       1       Jazz
6    31       1  Classical
7    33       1  Classical
8    37       1  Classical
9    20       0      Dance
10   21       0      Dance
11   25       0      Dance
12   26       0   Acoustic
13   27       0   Acoustic
14   30       0   Acoustic
15   31       0  Classical
16   34       0  Classical
17   35       0  Classical

In [30]:
# step 3 cleaning or preparing of the data set
# we need to divide our data into input-set and output-set
X = music_data.drop(columns=['genre']) # this will create new dataset without having genre
#by convension we use capital X to represent this new dataset

In [203]:
y  = music_data['genre']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1)


# Step 4 use a Model using a Machine Learning Algorithm
# step 5 make the predictions


# In this we used entire dataset.
model = DecisionTreeClassifier()
#model.fit(X.values, y)          # error removed  serWarning: X does not have valid feature 
model.fit(X_train,y_train)
#predictions = model.predict([[21, 1], [22, 0]])   Two samples passed.
predictions = model.predict(X_test)
#predictions

# Step 06. To find the accuracy we devide the data set into two portions 80% and 20% normally.
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
predictions = model.predict(X_test)
score = accuracy_score(y_test, predictions)
percent = score*100
print("Accuracy is:", percent ,"%")

Accuracy is: 50.0 %